# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install: travis_retry pip install -r dev-requirements.txt

script: python setup.py test
