# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "3.3"
  - "3.4"

install:
    - travis_retry pip install -r dev-requirements.txt
    - travis_retry invoke plugin_requirements
    - travis_retry python mfr/cli.py install all
    - pip install .

script: python setup.py test
