language: python

python:
  - "3.4"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

before_install:
    - export WHEELHOUSE=$HOME/wheelhouse

install:
    - travis_retry pip install invoke
    - travis_retry invoke wheelhouse --develop
    - travis_retry invoke install --develop

env:
  - MFR_CONFIG=./travis-config.json

script:
  - invoke test

notifications:
  flowdock: 0221882cdda034c0e9ac2a0e766053dd
